#!/bin/sh
SRC=$(realpath "$0")
DIR=$(dirname "$SRC")

if [ $# != 3 ]; then
   echo 1>&2 usage: $(basename "$SRC") [-1 FILE OUTPUT] [FILE INPUT-PIPE OUTPUT-PIPE]
   exit 1
fi
if [ "$1" = "-1" ]; then
    yq -o=json -I=0 . < "$FILE" > "$OUT"
    exit
fi
FILE="$1"
OUT="$2"
IN="$3"
TMPDIR=$(mktemp -d)
SCRATCH="$TMPDIR/scratch"
SCRATCHTEST="$TMPDIR/scratchtest"
SCRATCH2="$TMPDIR/scratch2"
FILETEST="$TMPDIR/filetest"
touch "$FILETEST"
touch "$SCRATCH"
touch "$SCRATCHTEST"

filemod() {
    stat -c %Y "$FILE"
}

waitforfilechange() {
    if [ "$2" -nt "$1" ]; then
        evt=$(inotifywait -qq -e close_write -e moved_from -e move -e move_self -e delete_self "$1")
        echo EVENT "$1" "$evt"
        touch "$2"
    fi
}

monitorfile() {
    while true; do
        waitforfilechange "$FILE" "$FILETEST"
        echo WRITING OUTPUT
        yq -o=json -I=0 . < "$FILE" > "$OUT"
        touch "$FILETEST"
    done
}

monitor() {
    while true; do
        yq -P < "$IN" > "$SCRATCH"
        touch "$FILETEST"
        mv "$SCRATCH" "$FILE"
        echo GOT INPUT "$(cat "$FILE")"
    done
}

monitor&
MONITORPID="$!"
monitorfile&
MONITORFILEPID="$!"

trap "echo EXITING; kill $MONITORPID $MONITORFILEPID; rm -rf $TMPDIR" EXIT
trap exit INT TERM

echo SENDING $"FILE" to "$OUT"
yq -o=json -I=0 . < "$FILE" > "$OUT"
wait
