#!/bin/sh

# Run redis
# trim all streams every PERIOD seconds

if [ $# != 2 ]; then
    echo usage: $(basename "$0") CACHEDIR STREAM
    exit 1
fi
DIR=$(dirname "$(realpath "$0")")
CACHEDIR="$(realpath "${1:-$DIR}")"
mkdir -p "$CACHEDIR"
#PERIOD=120
PERIOD=15
VERBOSITY=1

trimall() {
    while true; do
        for stream in $(redis-cli --json SCAN 0 TYPE stream | jq -c ".[1][]|."); do
            #echo trim $stream
            "$DIR/trim" "$stream" ${PERIOD}000
        done
        sleep $PERIOD
    done
}

die() {
    rm -f "$CACHEDIR/dump.rdb"
    echo EXITING
    kill $*
    redis-cli shutdown
}

(sleep 5; trimall)&
TRIM=$!
cd "$CACHEDIR"
redis-server 2>&1 > "$CACHEDIR/redis.log" &
trap "die $TRIM" EXIT
trap exit INT TERM
sleep 1
STREAM=$2
shift 2
julia -i -e 'println("STARTING REDIS LISTENER"); using Revise, Pkg; Pkg.activate("'"$DIR"'"); include(popfirst!(ARGS)); con=test("'$STREAM'", "'$STREAM'"; verbosity='$VERBOSITY'); println("Connection is stored in `con`")' "$DIR/redismain.jl" "$@"
