#!/bin/sh
# run the pipey example with input and output pipes

dir="$(dirname "$(realpath "$0")")"
src="$(dirname "$dir")"
if [ $# != 2 ]; then
   echo 1>&2 Usage: $(basename "$0") INPUTPIPE OUTPUTPIPE
   exit 1
fi
exec julia --project="$src" -e 'include(popfirst!(ARGS)); test()' "$dir/pipeymain.jl" "$@"
